# Configuración de SQLite
spring.datasource.url=jdbc:sqlite:notificaciones-test.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Permite que Hibernate cree la tabla automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# Título para la documentación Swagger
springdoc.swagger-ui.path=/swagger-ui.html